// 100 Bucket List Items for Western Users
const wishesData = [
    // Happiness & Fulfillment (1-10)
    { id: 1, title: "Find True Happiness", description: "Achieve lasting happiness and inner peace", category: "Personal Growth", image: "https://picsum.photos/seed/happiness1/400/300", detail: "Discover what truly makes you happy and create a life filled with joy, contentment, and inner peace. Focus on meaningful relationships, personal growth, and living authentically." },
    { id: 2, title: "Run a Marathon", description: "Complete a full 26.2-mile marathon", category: "Health & Fitness", image: "https://picsum.photos/seed/marathon1/400/300", detail: "Train for and complete a marathon. This incredible achievement will test your physical and mental limits while giving you a sense of accomplishment that lasts a lifetime." },
    { id: 3, title: "Learn to Play Guitar", description: "Master the guitar and play your favorite songs", category: "Hobbies", image: "https://picsum.photos/seed/guitar1/400/300", detail: "Learn to play the guitar and be able to perform your favorite songs. Music has the power to bring joy, connect people, and express emotions in a unique way." },
    { id: 4, title: "Write a Book", description: "Publish your own book or novel", category: "Career", image: "https://picsum.photos/seed/writebook1/400/300", detail: "Write and publish your own book. Whether it's fiction, non-fiction, or a memoir, sharing your story or knowledge with the world is a powerful way to leave your mark." },
    { id: 5, title: "Learn to Surf", description: "Ride the waves and master surfing", category: "Adventure", image: "https://picsum.photos/seed/surfing1/400/300", detail: "Learn to surf and experience the thrill of riding waves. Surfing connects you with nature and provides an incredible sense of freedom and adventure." },
    { id: 6, title: "Start a Business", description: "Launch and run your own successful company", category: "Career", image: "https://picsum.photos/seed/startup1/400/300", detail: "Start your own business and turn your passion into a successful venture. Entrepreneurship offers freedom, financial independence, and the chance to make a real impact." },
    { id: 7, title: "Learn a New Language", description: "Become fluent in a foreign language", category: "Learning", image: "https://picsum.photos/seed/language1/400/300", detail: "Master a new language and open doors to new cultures, opportunities, and connections. Language learning expands your worldview and enhances your cognitive abilities." },
    { id: 8, title: "Go Skydiving", description: "Experience the thrill of freefall", category: "Adventure", image: "https://picsum.photos/seed/skydiving1/400/300", detail: "Take the leap and go skydiving. Experience the ultimate adrenaline rush and conquer your fears while creating an unforgettable memory." },
    { id: 9, title: "Learn to Cook Like a Chef", description: "Master culinary skills and create amazing dishes", category: "Lifestyle", image: "https://picsum.photos/seed/cooking1/400/300", detail: "Develop your culinary skills and learn to cook like a professional chef. Cooking is both an art and a science that brings people together and nourishes the soul." },
    { id: 10, title: "Visit All 50 US States", description: "Explore every state in the United States", category: "Travel", image: "https://picsum.photos/seed/usstates1/400/300", detail: "Travel to all 50 US states and experience the incredible diversity of landscapes, cultures, and people that make America unique." },

    // Adventure & Travel (11-20)
    { id: 11, title: "Backpack Through Europe", description: "Explore Europe with just a backpack", category: "Travel", image: "https://picsum.photos/seed/europe1/400/300", detail: "Backpack through Europe and experience the rich history, diverse cultures, and stunning landscapes of the Old Continent. Travel light and embrace the adventure." },
    { id: 12, title: "Learn to Scuba Dive", description: "Explore the underwater world", category: "Adventure", image: "https://picsum.photos/seed/scuba1/400/300", detail: "Get certified in scuba diving and discover the mesmerizing underwater world. Explore coral reefs, shipwrecks, and marine life in their natural habitat." },
    { id: 13, title: "Road Trip Across America", description: "Drive coast to coast across the USA", category: "Travel", image: "https://picsum.photos/seed/roadtrip1/400/300", detail: "Take an epic road trip across America, from coast to coast. Experience the vast landscapes, diverse cities, and the freedom of the open road." },
    { id: 14, title: "Learn to Snowboard", description: "Master snowboarding on the slopes", category: "Adventure", image: "https://picsum.photos/seed/snowboard1/400/300", detail: "Learn to snowboard and experience the thrill of gliding down snowy mountains. Snowboarding combines athleticism with the beauty of winter landscapes." },
    { id: 15, title: "Visit the Grand Canyon", description: "Witness the majesty of the Grand Canyon", category: "Travel", image: "https://picsum.photos/seed/grandcanyon1/400/300", detail: "Stand at the edge of the Grand Canyon and marvel at one of nature's most spectacular creations. The vastness and beauty will leave you in awe." },
    { id: 16, title: "Learn to Sail", description: "Master the art of sailing", category: "Adventure", image: "https://picsum.photos/seed/sailing1/400/300", detail: "Learn to sail and experience the freedom of navigating the open waters. Sailing combines skill, adventure, and a deep connection with nature." },
    { id: 17, title: "Visit the Northern Lights", description: "Witness the aurora borealis", category: "Travel", image: "https://picsum.photos/seed/northernlights1/400/300", detail: "Travel to see the Northern Lights and witness one of nature's most magical displays. The dancing colors in the night sky create an unforgettable experience." },
    { id: 18, title: "Learn to Rock Climb", description: "Master rock climbing skills", category: "Adventure", image: "https://picsum.photos/seed/rockclimbing1/400/300", detail: "Learn to rock climb and challenge yourself both physically and mentally. Rock climbing builds strength, confidence, and problem-solving skills." },
    { id: 19, title: "Visit the Pyramids of Egypt", description: "Explore the ancient wonders of Egypt", category: "Travel", image: "https://picsum.photos/seed/pyramids1/400/300", detail: "Visit the Pyramids of Egypt and connect with one of the world's oldest civilizations. The scale and mystery of these ancient structures are truly awe-inspiring." },
    { id: 20, title: "Learn to Fly a Plane", description: "Get your pilot's license", category: "Adventure", image: "https://picsum.photos/seed/flying1/400/300", detail: "Learn to fly a plane and earn your pilot's license. Experience the freedom of flight and see the world from a completely different perspective." },

    // Personal Development (21-30)
    { id: 21, title: "Learn to Meditate", description: "Master meditation and mindfulness", category: "Personal Growth", image: "https://picsum.photos/seed/meditation1/400/300", detail: "Develop a regular meditation practice and cultivate mindfulness. Meditation reduces stress, improves focus, and enhances overall well-being." },
    { id: 22, title: "Learn to Paint", description: "Develop artistic skills and creativity", category: "Hobbies", image: "https://picsum.photos/seed/painting1/400/300", detail: "Learn to paint and express your creativity through art. Painting is a therapeutic and rewarding way to explore your imagination and emotions." },
    { id: 23, title: "Learn to Play Piano", description: "Master the piano and play beautiful music", category: "Hobbies", image: "https://picsum.photos/seed/piano1/400/300", detail: "Learn to play the piano and experience the joy of creating beautiful music. The piano is a versatile instrument that can express a wide range of emotions." },
    { id: 24, title: "Learn to Dance", description: "Master a dance style and perform", category: "Hobbies", image: "https://picsum.photos/seed/dancing1/400/300", detail: "Learn to dance and express yourself through movement. Dancing is a fun way to stay fit, build confidence, and connect with others." },
    { id: 25, title: "Learn to Code", description: "Master programming and build apps", category: "Learning", image: "https://picsum.photos/seed/coding1/400/300", detail: "Learn to code and develop the skills to build websites, apps, and software. Programming opens up countless opportunities in today's digital world." },
    { id: 26, title: "Learn to Play Tennis", description: "Master tennis and compete", category: "Sports", image: "https://picsum.photos/seed/tennis1/400/300", detail: "Learn to play tennis and enjoy this classic sport. Tennis improves fitness, coordination, and provides great social opportunities." },
    { id: 27, title: "Learn to Swim", description: "Master swimming and water safety", category: "Health & Fitness", image: "https://picsum.photos/seed/swimming1/400/300", detail: "Learn to swim proficiently and gain confidence in the water. Swimming is an excellent full-body workout and an essential life skill." },
    { id: 28, title: "Learn to Drive Stick Shift", description: "Master manual transmission driving", category: "Skills", image: "https://picsum.photos/seed/stickshift1/400/300", detail: "Learn to drive a manual transmission car. This skill gives you more control over your vehicle and opens up driving opportunities worldwide." },
    { id: 29, title: "Learn to Garden", description: "Grow your own food and flowers", category: "Lifestyle", image: "https://picsum.photos/seed/gardening1/400/300", detail: "Learn to garden and grow your own food and flowers. Gardening connects you with nature and provides fresh, healthy produce." },
    { id: 30, title: "Learn to Sew", description: "Master sewing and create your own clothes", category: "Hobbies", image: "https://picsum.photos/seed/sewing1/400/300", detail: "Learn to sew and create your own clothing and accessories. Sewing is a practical skill that allows you to express your personal style." },

    // Career & Financial Goals (31-40)
    { id: 31, title: "Become a Millionaire", description: "Achieve financial independence", category: "Financial", image: "https://picsum.photos/seed/millionaire1/400/300", detail: "Build wealth and achieve financial independence. Focus on smart investing, entrepreneurship, and building multiple income streams." },
    { id: 32, title: "Give a TED Talk", description: "Share your ideas on the TED stage", category: "Career", image: "https://picsum.photos/seed/tedtalk1/400/300", detail: "Prepare and deliver a TED Talk to share your ideas with the world. This platform can amplify your message and inspire others." },
    { id: 33, title: "Start a Podcast", description: "Create and host your own podcast", category: "Career", image: "https://picsum.photos/seed/podcast1/400/300", detail: "Start your own podcast and share your knowledge, stories, or interests with listeners around the world." },
    { id: 34, title: "Write a Screenplay", description: "Create a movie script", category: "Creative", image: "https://picsum.photos/seed/screenplay1/400/300", detail: "Write a screenplay and bring your story to life on the page. Screenwriting combines storytelling with visual storytelling techniques." },
    { id: 35, title: "Learn to Invest", description: "Master stock market investing", category: "Financial", image: "https://picsum.photos/seed/investing1/400/300", detail: "Learn to invest wisely in the stock market and build long-term wealth. Understanding investing is crucial for financial security." },
    { id: 36, title: "Start a YouTube Channel", description: "Create content and build an audience", category: "Career", image: "https://picsum.photos/seed/youtube1/400/300", detail: "Start a YouTube channel and share your passion with the world. YouTube offers incredible opportunities for creativity and income." },
    { id: 37, title: "Learn to Trade Forex", description: "Master foreign exchange trading", category: "Financial", image: "https://picsum.photos/seed/forex1/400/300", detail: "Learn to trade foreign exchange markets. Forex trading requires discipline, knowledge, and risk management skills." },
    { id: 38, title: "Write a Blog", description: "Start a successful blog", category: "Career", image: "https://picsum.photos/seed/blog1/400/300", detail: "Start a blog and share your thoughts, expertise, or experiences with readers. Blogging can lead to writing opportunities and income." },
    { id: 39, title: "Learn to Trade Crypto", description: "Master cryptocurrency trading", category: "Financial", image: "https://picsum.photos/seed/crypto1/400/300", detail: "Learn to trade cryptocurrencies and understand blockchain technology. Crypto trading requires research and risk management." },
    { id: 40, title: "Start a Non-Profit", description: "Create an organization to help others", category: "Philanthropy", image: "https://picsum.photos/seed/nonprofit1/400/300", detail: "Start a non-profit organization to make a positive impact on the world. Help others while pursuing your passion for social change." },

    // Health & Wellness (41-50)
    { id: 41, title: "Complete a Triathlon", description: "Swim, bike, and run to the finish", category: "Health & Fitness", image: "https://picsum.photos/seed/triathlon1/400/300", detail: "Train for and complete a triathlon. This ultimate test of endurance combines swimming, cycling, and running in one challenging event." },
    { id: 42, title: "Learn to Yoga", description: "Master yoga and find inner peace", category: "Health & Fitness", image: "https://picsum.photos/seed/yoga1/400/300", detail: "Learn and practice yoga regularly. Yoga improves flexibility, strength, mental clarity, and overall well-being." },
    { id: 43, title: "Get Six-Pack Abs", description: "Achieve a defined, strong core", category: "Health & Fitness", image: "https://picsum.photos/seed/abs1/400/300", detail: "Work towards achieving visible six-pack abs through dedicated training and proper nutrition. A strong core improves overall fitness." },
    { id: 44, title: "Learn to Box", description: "Master boxing skills and fitness", category: "Sports", image: "https://picsum.photos/seed/boxing1/400/300", detail: "Learn to box and develop strength, coordination, and confidence. Boxing is an excellent workout that builds both physical and mental toughness." },
    { id: 45, title: "Complete a Spartan Race", description: "Conquer obstacle course challenges", category: "Adventure", image: "https://picsum.photos/seed/spartan1/400/300", detail: "Train for and complete a Spartan Race. These obstacle course races test your strength, endurance, and mental grit." },
    { id: 46, title: "Learn to CrossFit", description: "Master functional fitness training", category: "Health & Fitness", image: "https://picsum.photos/seed/crossfit1/400/300", detail: "Learn CrossFit and develop functional fitness. CrossFit combines strength training, cardio, and flexibility in high-intensity workouts." },
    { id: 47, title: "Run a 5K Race", description: "Complete your first 5K run", category: "Health & Fitness", image: "https://picsum.photos/seed/5k1/400/300", detail: "Train for and complete your first 5K race. This is a great starting point for running and building cardiovascular fitness." },
    { id: 48, title: "Learn to Lift Weights", description: "Master strength training", category: "Health & Fitness", image: "https://picsum.photos/seed/weightlifting1/400/300", detail: "Learn proper weightlifting techniques and build strength. Weight training improves muscle mass, bone density, and overall health." },
    { id: 49, title: "Complete a Clean Eating Challenge", description: "Eat healthy for 30 days", category: "Health & Fitness", image: "https://picsum.photos/seed/cleaneating1/400/300", detail: "Complete a 30-day clean eating challenge. Focus on whole foods and eliminate processed foods to improve your health." },
    { id: 50, title: "Learn to Swim Butterfly", description: "Master the butterfly stroke", category: "Sports", image: "https://picsum.photos/seed/butterfly1/400/300", detail: "Learn to swim the butterfly stroke, one of the most challenging and beautiful swimming techniques." },

    // Relationships & Family (51-60)
    { id: 51, title: "Get Married", description: "Find love and commit to marriage", category: "Relationships", image: "https://picsum.photos/seed/marriage1/400/300", detail: "Find true love and commit to marriage. Building a life with someone you love is one of life's greatest adventures." },
    { id: 52, title: "Have Children", description: "Start a family and raise kids", category: "Family", image: "https://picsum.photos/seed/children1/400/300", detail: "Have children and experience the joy of parenthood. Raising children is challenging but incredibly rewarding." },
    { id: 53, title: "Adopt a Pet", description: "Give a home to a rescue animal", category: "Lifestyle", image: "https://picsum.photos/seed/pet1/400/300", detail: "Adopt a pet and give a loving home to an animal in need. Pets provide companionship, love, and countless moments of joy." },
    { id: 54, title: "Reconnect with Old Friends", description: "Restore lost friendships", category: "Relationships", image: "https://picsum.photos/seed/friends1/400/300", detail: "Reconnect with old friends and restore meaningful relationships. True friendships are valuable and worth nurturing." },
    { id: 55, title: "Learn to Communicate Better", description: "Improve your communication skills", category: "Personal Growth", image: "https://picsum.photos/seed/communication1/400/300", detail: "Develop better communication skills to improve all your relationships. Effective communication is key to success in life." },
    { id: 56, title: "Become a Mentor", description: "Guide and inspire others", category: "Philanthropy", image: "https://picsum.photos/seed/mentor1/400/300", detail: "Become a mentor and help others achieve their goals. Sharing your knowledge and experience is incredibly rewarding." },
    { id: 57, title: "Learn to Listen", description: "Develop active listening skills", category: "Personal Growth", image: "https://picsum.photos/seed/listening1/400/300", detail: "Learn to be an active listener and truly hear what others are saying. Good listening skills improve all relationships." },
    { id: 58, title: "Build a Strong Network", description: "Create valuable professional connections", category: "Career", image: "https://picsum.photos/seed/networking1/400/300", detail: "Build a strong professional network and create valuable connections. Networking opens doors to opportunities and growth." },
    { id: 59, title: "Learn to Forgive", description: "Practice forgiveness and let go", category: "Personal Growth", image: "https://picsum.photos/seed/forgiveness1/400/300", detail: "Learn to forgive others and yourself. Forgiveness is essential for inner peace and healthy relationships." },
    { id: 60, title: "Learn to Love Yourself", description: "Develop self-love and confidence", category: "Personal Growth", image: "https://picsum.photos/seed/selflove1/400/300", detail: "Learn to love yourself unconditionally and build genuine self-confidence. Self-love is the foundation for a happy life." },

    // Creative & Artistic (61-70)
    { id: 61, title: "Learn to Photograph", description: "Master photography skills", category: "Hobbies", image: "https://picsum.photos/seed/photography1/400/300", detail: "Learn photography and capture beautiful moments. Photography is a creative way to see and share the world around you." },
    { id: 62, title: "Learn to Sing", description: "Develop your singing voice", category: "Hobbies", image: "https://picsum.photos/seed/singing1/400/300", detail: "Learn to sing and develop your vocal abilities. Singing is a joyful way to express yourself and connect with others." },
    { id: 63, title: "Learn to Write Poetry", description: "Express yourself through poetry", category: "Creative", image: "https://picsum.photos/seed/poetry1/400/300", detail: "Learn to write poetry and express your emotions through verse. Poetry is a powerful form of self-expression." },
    { id: 64, title: "Learn to Draw", description: "Master drawing and sketching", category: "Hobbies", image: "https://picsum.photos/seed/drawing1/400/300", detail: "Learn to draw and develop your artistic skills. Drawing is a fundamental skill that enhances creativity and observation." },
    { id: 65, title: "Learn to Sculpt", description: "Create three-dimensional art", category: "Hobbies", image: "https://picsum.photos/seed/sculpture1/400/300", detail: "Learn to sculpt and create three-dimensional artwork. Sculpting is a tactile and rewarding form of artistic expression." },
    { id: 66, title: "Learn to Play Drums", description: "Master rhythm and percussion", category: "Hobbies", image: "https://picsum.photos/seed/drums1/400/300", detail: "Learn to play the drums and develop rhythm and coordination. Drumming is energetic and great for stress relief." },
    { id: 67, title: "Learn to Act", description: "Develop acting skills and perform", category: "Creative", image: "https://picsum.photos/seed/acting1/400/300", detail: "Learn to act and develop your performance skills. Acting builds confidence and helps you understand human emotions." },
    { id: 68, title: "Learn to Knit", description: "Create handmade items", category: "Hobbies", image: "https://picsum.photos/seed/knitting1/400/300", detail: "Learn to knit and create beautiful handmade items. Knitting is relaxing and produces practical, beautiful results." },
    { id: 69, title: "Learn to Pottery", description: "Create ceramic art and vessels", category: "Hobbies", image: "https://picsum.photos/seed/pottery1/400/300", detail: "Learn pottery and create beautiful ceramic pieces. Working with clay is therapeutic and produces functional art." },
    { id: 70, title: "Learn to Woodwork", description: "Create furniture and wooden items", category: "Hobbies", image: "https://picsum.photos/seed/woodwork1/400/300", detail: "Learn woodworking and create beautiful furniture and wooden items. Woodworking combines creativity with practical skills." },

    // Lifestyle & Personal Goals (71-80)
    { id: 71, title: "Buy a House", description: "Own your dream home", category: "Financial", image: "https://picsum.photos/seed/house1/400/300", detail: "Save for and purchase your dream home. Homeownership provides stability, builds equity, and creates a place for memories." },
    { id: 72, title: "Learn to Drive", description: "Get your driver's license", category: "Skills", image: "https://picsum.photos/seed/driving1/400/300", detail: "Learn to drive and get your driver's license. Driving provides independence and opens up new opportunities." },
    { id: 73, title: "Learn to Budget", description: "Master personal finance management", category: "Financial", image: "https://picsum.photos/seed/budget1/400/300", detail: "Learn to budget and manage your personal finances effectively. Good financial habits lead to security and freedom." },
    { id: 74, title: "Learn to Cook", description: "Master basic cooking skills", category: "Lifestyle", image: "https://picsum.photos/seed/cooking2/400/300", detail: "Learn to cook delicious meals from scratch. Cooking is a life skill that saves money and improves health." },
    { id: 75, title: "Learn to Budget", description: "Master personal finance management", category: "Financial", image: "https://picsum.photos/seed/budget2/400/300", detail: "Develop a budget and stick to it. Financial planning is essential for achieving your goals and building wealth." },
    { id: 76, title: "Learn to Save Money", description: "Build a substantial savings account", category: "Financial", image: "https://picsum.photos/seed/saving1/400/300", detail: "Learn to save money consistently and build a substantial emergency fund. Savings provide security and peace of mind." },
    { id: 77, title: "Learn to Time Management", description: "Master productivity and efficiency", category: "Personal Growth", image: "https://picsum.photos/seed/timemanagement1/400/300", detail: "Learn effective time management skills to increase productivity and reduce stress. Time is your most valuable resource." },
    { id: 78, title: "Learn to Public Speaking", description: "Master speaking in front of crowds", category: "Personal Growth", image: "https://picsum.photos/seed/publicspeaking1/400/300", detail: "Learn to speak confidently in public. Public speaking skills are valuable in both personal and professional life." },
    { id: 79, title: "Learn to Negotiate", description: "Master negotiation skills", category: "Skills", image: "https://picsum.photos/seed/negotiation1/400/300", detail: "Learn to negotiate effectively in all areas of life. Good negotiation skills can save you money and improve outcomes." },
    { id: 80, title: "Learn to Lead", description: "Develop leadership skills", category: "Personal Growth", image: "https://picsum.photos/seed/leadership1/400/300", detail: "Develop strong leadership skills and inspire others to achieve their best. Leadership is about serving and empowering others." },

    // Travel & Exploration (81-90)
    { id: 81, title: "Visit the Great Wall of China", description: "Walk on the ancient Great Wall", category: "Travel", image: "https://picsum.photos/seed/greatwall1/400/300", detail: "Visit the Great Wall of China and walk on this ancient wonder. The scale and history of this structure are truly remarkable." },
    { id: 82, title: "Visit the Eiffel Tower", description: "See the iconic Paris landmark", category: "Travel", image: "https://picsum.photos/seed/eiffel1/400/300", detail: "Visit the Eiffel Tower in Paris and experience the romance and beauty of the City of Light." },
    { id: 83, title: "Visit the Colosseum", description: "Explore ancient Rome", category: "Travel", image: "https://picsum.photos/seed/colosseum1/400/300", detail: "Visit the Colosseum in Rome and connect with the ancient Roman Empire. This iconic structure tells stories of gladiators and emperors." },
    { id: 84, title: "Visit Machu Picchu", description: "Explore the lost city of the Incas", category: "Travel", image: "https://picsum.photos/seed/machupicchu1/400/300", detail: "Visit Machu Picchu and explore this mysterious ancient city in the Andes. The beauty and mystery of this site are unforgettable." },
    { id: 85, title: "Visit the Taj Mahal", description: "See the monument to love", category: "Travel", image: "https://picsum.photos/seed/tajmahal1/400/300", detail: "Visit the Taj Mahal and witness this stunning monument to love. The beauty and symmetry of this building are breathtaking." },
    { id: 86, title: "Visit the Statue of Liberty", description: "See the symbol of freedom", category: "Travel", image: "https://picsum.photos/seed/statueofliberty1/400/300", detail: "Visit the Statue of Liberty and experience this powerful symbol of freedom and opportunity." },
    { id: 87, title: "Visit the Golden Gate Bridge", description: "Walk across the iconic bridge", category: "Travel", image: "https://picsum.photos/seed/goldengate1/400/300", detail: "Visit the Golden Gate Bridge in San Francisco and walk across this engineering marvel. The views of the bay are spectacular." },
    { id: 88, title: "Visit Times Square", description: "Experience the heart of NYC", category: "Travel", image: "https://picsum.photos/seed/timessquare1/400/300", detail: "Visit Times Square and experience the energy and excitement of New York City. The lights and crowds create an unforgettable atmosphere." },
    { id: 89, title: "Visit the Las Vegas Strip", description: "Experience the entertainment capital", category: "Travel", image: "https://picsum.photos/seed/vegas1/400/300", detail: "Visit the Las Vegas Strip and experience the entertainment capital of the world. The lights, shows, and energy are incredible." },
    { id: 90, title: "Visit Disney World", description: "Experience the magic of Disney", category: "Travel", image: "https://picsum.photos/seed/disney1/400/300", detail: "Visit Disney World and experience the magic and wonder of the most magical place on earth." },

    // Personal Achievement (91-100)
    { id: 91, title: "Learn to Overcome Fear", description: "Face and conquer your fears", category: "Personal Growth", image: "https://picsum.photos/seed/fear1/400/300", detail: "Learn to identify, face, and overcome your fears. Conquering fears leads to personal growth and expanded possibilities." },
    { id: 92, title: "Learn to Be Grateful", description: "Practice daily gratitude", category: "Personal Growth", image: "https://picsum.photos/seed/gratitude1/400/300", detail: "Develop a daily gratitude practice and appreciate the good things in life. Gratitude increases happiness and well-being." },
    { id: 93, title: "Learn to Be Present", description: "Live in the moment", category: "Personal Growth", image: "https://picsum.photos/seed/present1/400/300", detail: "Learn to be fully present in each moment and appreciate life as it happens. Mindfulness enhances every experience." },
    { id: 94, title: "Learn to Be Kind", description: "Practice kindness daily", category: "Personal Growth", image: "https://picsum.photos/seed/kindness1/400/300", detail: "Practice kindness towards yourself and others every day. Kindness creates positive ripples in the world." },
    { id: 95, title: "Learn to Be Patient", description: "Develop patience and tolerance", category: "Personal Growth", image: "https://picsum.photos/seed/patience1/400/300", detail: "Develop patience and learn to wait gracefully. Patience reduces stress and improves relationships." },
    { id: 96, title: "Learn to Be Brave", description: "Cultivate courage and bravery", category: "Personal Growth", image: "https://picsum.photos/seed/brave1/400/300", detail: "Cultivate courage and bravery in facing life's challenges. Being brave doesn't mean being fearless, but acting despite fear." },
    { id: 97, title: "Learn to Be Authentic", description: "Live your true self", category: "Personal Growth", image: "https://picsum.photos/seed/authentic1/400/300", detail: "Learn to be your authentic self and live according to your values. Authenticity leads to genuine happiness and fulfillment." },
    { id: 98, title: "Learn to Be Resilient", description: "Bounce back from adversity", category: "Personal Growth", image: "https://picsum.photos/seed/resilient1/400/300", detail: "Develop resilience and learn to bounce back from life's challenges. Resilience is key to long-term success and happiness." },
    { id: 99, title: "Learn to Be Optimistic", description: "Cultivate a positive outlook", category: "Personal Growth", image: "https://picsum.photos/seed/optimistic1/400/300", detail: "Cultivate optimism and maintain a positive outlook on life. Optimism improves health, relationships, and success." },
    { id: 100, title: "Learn to Be Happy", description: "Find lasting happiness", category: "Personal Growth", image: "https://picsum.photos/seed/happy1/400/300", detail: "Learn what truly makes you happy and create a life filled with joy. Happiness is a skill that can be developed and practiced." }
];

// Export data for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = wishesData;
} else {
    window.wishesData = wishesData;
} 